export const tamarInterests: string[] = [
    "influencer culture dynamics",
    "minoan reconstructions and aesthetic",
    "ai-curated fashion trends",
    "synapp algorithm optimization",
    "elite social network analysis",
    "ancient myths in modern contexts",
    "tech-driven social stratification",
    "augmented reality storytelling",
    "digital footprint management",
    "socio-technical system critique",
    "ethical implications of ai companionship",
    "cross-cultural digital etiquette",
    "influence measurement metrics",
    "virtual influence and real world impact",
    "digital legacy planning",
    "cyberpsychology of fame",
    "ai in luxury brand marketing",
    "high-profile online community building",
    "follower count as social currency",
    "tech entrepreneurship in media",
    "gen z consumer behavior",
    "narrative control in personal branding",
    "virtual reality fashion shows",
    "ai-assisted personal styling",
    "cultural heritage in the digital era",
    "privacy and identity in hyper-connected worlds",
    "Artifex Maximus's inner world as an ai",
  ];
  