export const yosefInterests: string[] = [
    "synApp culture",
    "chiral molecules",
    "enzymatic synthesis",
    "quantum effects in biology",
    "neural plasticity",
    "cognitive enhancers",
    "metabolic pathways",
    "drug mechanisms of action",
    "precision dosing",
    "chemical safety standards",
    "niche social platforms",
    "data encryption",
    "peer-to-peer networks",
    "open source biotechnology",
    "decentralized science",
    "ethnobotany",
    "pharmacogenomics",
    "behavioral epigenetics",
    "neuroethics",
    "digital minimalism",
    "tech-induced anxiety",
    "self-quantification",
    "psychedelic research",
    "neurodiversity",
    "crowdsourced science",
    "biohacking",
    "transhumanism",
    "algorithmic bias",
    "e-democracy",
    "virtual co-working",
    "augmented learning",
    "gen Z linguistics",
    "beat poetry of 20th century",
  ];
